version: '3.8'

services:
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: node-backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
    environment:
      MONGO_URI: mongodb+srv://s6604062610489:Pete10489@cluster.1d3btnv.mongodb.net/
    depends_on:
      - backend-deps

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend-deps:
    image: alpine
    command: echo "Backend dependencies are ready"